### ISSUE TITLE
public web endoints not available

### ISSUE THREAD

**Issue by chuegel** [Keyfactor/ejbca-community-helm#10]
The ingress points to the path `/ejbca` but this endpoint is not available in the container leading to a `404 not found` error
According to the documentation, this endoinds should be exposed: https://doc.primekey.com/ejbca/ejbca-installation/application-servers/wildfly-26#WildFly26-EJBCAServices

Following services lead to `404 not found`
Service | Protocol | URL | Comment
-- | -- | -- | --
EJBCA Public web pages | HTTP, HTTPS | http[s]://{hostname}/ejbca <br> http[s]://{hostname}/ejbca/enrol <br>http[s]://{hostname}/ejbca/retrieve<br> http[s]://{hostname}/ejbca/inspect
EJBCA documentation | HTTP, HTTPS | http[s]://{hostname}/ejbca/doc

**Comment by svenska-primekey** [comment]
The public web was deprecated in EJBCA 8.0. The doc endpoint is not available in the container, only a software install. I'll get a ticket open to have the doc updated.
