### ISSUE TITLE
Consider adding more metadata or relying on some library chart

### ISSUE THREAD

**Issue by lazyoldbear** [Keyfactor/ejbca-community-helm#3]
I am particularly missing `podLabels`, `topologySpreadConstraints` and `updateStrategy`.

One way of addressing that and many other things is to reuse something, like Helmet or another library chart.

**Comment by svenska-primekey** [comment]
That's a good idea. Do you have some examples that you could share?

**Comment by lazyoldbear** [comment]
Hello. I am sorry for the long delay. 
Here's what I mean: https://github.com/Keyfactor/ejbca-community-helm/pull/11
Please note: I did not try to deploy, only made `helm template`. But I hope that serves the illustration purpose.

**Comment by lazyoldbear** [comment]
And, obviously, the same would apply to signserver.

**Comment by svenska-primekey** [comment]
Your changes look awesome! could you rebase the commit. I think I understand enough to update the readme. I would really like to get your PR merged. Thank you for the contribution!

**Comment by lazyoldbear** [comment]
Apologies for not filling the gaps with README. We are using most of those things ourselves. 
Perhaps what I forgot is `NetworkPolicy`, but I doubt it is critical.

**Comment by svenska-primekey** [comment]
Closing issue now that this is merged. Thank you @lazyoldbear for the contribution!
